
# GET genesis block
GET http://localhost:8000/block/0


###
POST http://localhost:8000/requestValidation
content-type: application/json

{
    "address": "myoJTcHCub3aLJ4aGmRzMGxbTUYHRAJJcF"
}

###
POST http://localhost:8000/submitStar
content-type: application/json

{
    "address": "myoJTcHCub3aLJ4aGmRzMGxbTUYHRAJJcF",
    "signature": "H2SdOATW8DEGuP7TQhpPyt77+auD1qcHNQTDNK2OVm/HJ9wF+qJaqUnftQa/3ufjZM12X50F3dSTdl2aTgTb0nw=",
    "message": "myoJTcHCub3aLJ4aGmRzMGxbTUYHRAJJcF:1577570780:starRegistry",
    "star": {
        "dec": "",
        "ra": "",
        "story": ""
    }
}

###
GET http://localhost:8000/blocks/myoJTcHCub3aLJ4aGmRzMGxbTUYHRAJJcF
content-type: application/json

###
GET http://localhost:8000/block/30fc39aa18f85d5619b9fdd9837da61590b6386963ebaf3fd18ab7c9975a0b66
content-type: application/json

###
GET http://localhost:8000/block/30fc39aa18f85d5619b9fdd9837da61590b6386963ebaf3fd18ab7c9975a0b66
content-type: application/json